# Standard deviation of position, east/north/up in meters.
geometry_msgs/Point position_std_dev

# Standard deviation of quaternion qx/qy/qz, unitless.
geometry_msgs/Point orientation_std_dev

# Standard deviation of linear velocity, east/north/up in meters per second.
geometry_msgs/Point linear_velocity_std_dev

# Standard deviation of linear acceleration, right/forward/up in meters per
# square second.
geometry_msgs/Point linear_acceleration_std_dev

# Standard deviation of angular velocity, right/forward/up in radians per
# second.
geometry_msgs/Point angular_velocity_std_dev

# TODO: Define covariance items when needed.